### ISSUE TITLE
units.hpp:38:20: error: ‘size_t’ does not name a type

### ISSUE THREAD

**Issue by jplatte** [zneak/units-cxx14#1]
Pretty self-explanatory, simply a missing include of `<cstddef>`.

Also, <strike>two</strike> three other small things:
- Is there a reason you don't have include guards? I guess you don't strictly need them, as your code is 100% templates, but it still seems to be reasonable to have them.
- Is there a reason the quantity constructors and const member functions aren't constexpr? It's the same thing for the non-member `operator*` and `operator/`.
- Why are `quantity& operator+=(quantity that)` and `quantity& operator-=(quantity that)` const?

Here's an updated version (I don't like PRs, just create your own commits, you can select individual changes using `-p` / `--patch` with git add): https://gist.github.com/jplatte/96cf29cba575d6e8de53

**Comment by fay59** [comment]
The answer to most of these questions is "I wrote this one day on my train commute". I'll gladly take your improvements.
