### ISSUE TITLE
degrees/radians

### ISSUE THREAD

**Issue by Trass3r** [zneak/units-cxx14#6]
Currently radians are commented out: `// skipping radian: rad = m / m`
and degrees result in a primitive type losing type safety.

``` cpp
void foo(decltype(deg) a)
{}
void unitstest()
{
    foo(5 * rad);
}
```

**Comment by fay59** [comment]
This is because angles are not first-class citizens of the SI. The SI explanation for radians is that they're meters divided by meters (which is what the `m / m` part of the comment is supposed to mean). That would be a unitless value, which doesn't provide any type safety over its numerical type. The same goes for steradians.

I do see the advantage of having real units for them, but I don't want to deviate too much from the SI without good justification (or technical reasons). I'm willing to reconsider it if several people who deal with SI units that need angles want radians as first-class citizens.

I would suggest that you create your own degrees and radians and gradians if you need them, and add them your `siunits.hpp` or within their own unit system.

**Comment by jplatte** [comment]
EDIT: I wrote bullshit, removed my old comment...

The basic problem is that both "raw" numbers and radians are unitless (I've found 'dimensionless' as well, I think it's the same, but not 100% sure). Boost.Units has some sort of solution for this, but I don't fully understand it, and adding it here might introduce more complexity than is justifiable.
Anyway, here's the link to a very brief explanation: http://www.boost.org/doc/libs/1_55_0/doc/html/boost_units/FAQ.html

**Comment by Trass3r** [comment]
The problem with boost is.. boost ;)
Cluttered with backwards compatibility garbage plus you can't even pull out a single file as everything is interdependent. It's so bad they even had to create a [tool](http://www.boost.org/tools/bcp/) just for that.
In contrast this library is very appealing. Tiny and slick.

@zneak
Yeah I guess putting radians into its own system would make more sense.
Combining it with most SI units makes only limited sense anyway.
But I wonder how you could prevent/fix things like

``` cpp
decltype(deg) degrees = 5 * rad;
decltype(kg) kilograms = 5 * g;
```

**Comment by fay59** [comment]
The library is _designed_ to allow it. You may want to take a look at the `recipe()` function of example.cpp.

The only place it will matter is where you try to get the numerical value behind the quantity. To do so, you divide it by a unit. If you want degrees out of your `degrees` variable, you divide it by `deg` (and you'll get about 286.479). If you want radias, you divide it by `rad` (and you'll get about 5).

**Comment by Trass3r** [comment]
Ha indeed, thanks for pointing out the division "trick".

**Comment by jplatte** [comment]
@Trass3r Just as a note, I know how horrible it is to work with Boost, that is why I switched to this library (and then started contributing). When I wanted to add constexpr in a few places in Boost.Units, I was advised to do a full clone of all of Boost first, and a shallow recursive clone of all of it was the only alternative... Which took forever, but worked. Until `btrfs balance` segfaulted a few days after and took half my FS with it. Then I gave up :D

But enough with the rambling... There actually is some use in having `rad` as part of the SI system, as there are units derived from it ([example](https://en.wikipedia.org/wiki/Angular_acceleration)). I'm still not sure whether it would make sense to do the same thing as Boost.Units here, though that won't change until I actually understand it... Did you have a look at it, @zneak?

**Comment by fay59** [comment]
Even within named units, lumens are defined as candela \* steradians, so we're definitely missing out on not having angles (or solid angles, for that matter).

I'm not familiar with units that use them, so it's hard for me to tell if you could make it work by defining radians and steradians as base units. It seems to me that if you need to derive the angle from distance (or area) quantities, it wouldn't work to have radians/steradians declared as their own thing. But then again, if it's simply not how you use them, then maybe it'd work.

Practically, it's a two-line change to have radians as a base unit in `siunits.hpp` (three if you want degrees too). I'd love to have feedback from someone who knows that stuff better to decide if it's a good idea to have it in by default or not. I'll see if my physicist friends have an opinion on that matter.

**Comment by Trass3r** [comment]
@jplatte yes rad/s and rad/s² are the only useful combinations that came to my mind too and in fact the ones I intended to use in the first place.

Also I'm currently playing with 2 ideas:

``` cpp
// define decltype(unit) wrappers which prevent direct construction
struct Angle final : decltype(rad) { Angle(decltype(rad) o) : decltype(rad)(o) {} };
struct Force final : decltype(N) { Force(decltype(N) o) : decltype(N)(o) {} };
void foo(Angle angle, Force force)
{
    // Angle b(5); // error : no matching constructor
    printf("%f in deg\n", angle[deg]);
    printf("%f in kN\n", force[std::kilo() * N]); // a bit nicer than divide syntax
}
```

**Comment by fay59** [comment]
Just to not leave you hanging, my physicist friend said that people do use `m/m` to produce radians, so I'm really uneasy about adding radians as units. If that won't be your case, you're of course welcome to add them to your local siunits, which should be 3ish lines of code. That's what I'm the most comfortable with for now.

Maybe we could `#ifdef` angles as first-class units.
